local cDir = shell.dir()
local function wget(url) 
    shell.run("wget "..url)
end
print("Installing Advanced Commands...")
shell.run("mkdir /moonlight/tmp/cmdinstaller_tmp")
shell.run("cd /moonlight/tmp/cmdinstaller_tmp")
wget("https://raw.githubusercontent.com/akki697222/Moonlight-CC-T-Linux-Like-OS/main/packages/advancedcmd/commands/cat.lua")
wget("https://raw.githubusercontent.com/akki697222/Moonlight-CC-T-Linux-Like-OS/main/packages/advancedcmd/commands/grep.lua")
wget("https://raw.githubusercontent.com/akki697222/Moonlight-CC-T-Linux-Like-OS/main/packages/advancedcmd/commands/echo.lua")
wget("https://raw.githubusercontent.com/akki697222/Moonlight-CC-T-Linux-Like-OS/main/packages/advancedcmd/commands/sudo.lua")
wget("https://raw.githubusercontent.com/akki697222/Moonlight-CC-T-Linux-Like-OS/main/packages/advancedcmd/commands/switchshell.lua")
shell.run("cp /moonlight/tmp/cmdinstaller_tmp/* /moonlight/bin")
shell.run("delete /moonlight/tmp/cmdinstaller_tmp")
shell.run("cd /"..cDir)
